spring.application.name=demo
spring.main.allow-bean-definition-overriding=true
spring.datasource.url=jdbc:sqlserver://localhost:57764;databaseName=SumergeTasks;trustServerCertificate=true
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver